/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/emails/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_emails__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Email Breaches */
        get: operations["get_email_breaches_emails__email__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/analytics/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Email Breach Analytics */
        get: operations["get_email_breach_analytics_emails_analytics__email__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/breaches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Breaches */
        get: operations["get_breaches_breaches__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/breaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Breaches */
        get: operations["get_breaches_breaches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/breaches/{breach_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Breach */
        get: operations["get_breach_breaches__breach_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index Store */
        get: operations["index_store_store__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/breach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Store Breach */
        get: operations["store_breach_store_breach_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Breach */
        Breach: {
            /** Breach Id */
            breach_id: string;
            /**
             * Breached Date
             * Format: date
             */
            breached_date: string;
            /** Domain */
            domain: string;
            /** Exposed Data */
            exposed_data: string[];
            /** Exposed Records */
            exposed_records: number | null;
            /** Exposure Description */
            exposure_description: string;
            /** Industry */
            industry: string;
            /** Logo */
            logo: string;
            /** Password Risk */
            password_risk: string;
            /** Reference Url */
            reference_url: string | null;
            /** Searchable */
            searchable: boolean;
            /** Sensitive */
            sensitive: boolean;
            /** Verified */
            verified: boolean;
        };
        /** BreachMetrics */
        BreachMetrics: {
            /** Get Details */
            get_details: string[];
            /** Industry */
            industry: (string | number)[][][];
            /** Passwords Strength */
            passwords_strength: {
                [key: string]: unknown;
            }[];
            /** Risk */
            risk: {
                [key: string]: unknown;
            }[];
            /** Xposed Data */
            xposed_data: {
                [key: string]: unknown;
            }[];
            /** Yearwise Details */
            yearwise_details: {
                [key: string]: unknown;
            }[];
        };
        /** Breaches */
        Breaches: {
            /** Exposedbreaches */
            exposedBreaches: components["schemas"]["Breach"][];
        };
        /** EmailBreachAnalytics */
        EmailBreachAnalytics: {
            BreachMetrics: components["schemas"]["BreachMetrics"];
            BreachesSummary: components["schemas"]["Summary"];
            ExposedBreaches: components["schemas"]["ExposedBreaches"];
            /** Exposedpastes */
            ExposedPastes: {
                [key: string]: unknown;
            } | null;
            /** Pastemetrics */
            PasteMetrics: {
                [key: string]: unknown;
            } | null;
            /** Pastessummary */
            PastesSummary: {
                [key: string]: unknown;
            };
        };
        /** EmailBreaches */
        EmailBreaches: {
            /** Breaches */
            breaches: string[][];
            /** Email */
            email: string;
            /** Status */
            status: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Error */
            Error: string;
            /** Email */
            email: string | null;
        };
        /** ExposedBreach */
        ExposedBreach: {
            /** Breach */
            breach: string;
            /** Details */
            details: string;
            /** Domain */
            domain: string;
            /** Industry */
            industry: string;
            /** Logo */
            logo: string;
            /** Password Risk */
            password_risk: string;
            /** References */
            references: string;
            /** Searchable */
            searchable: string;
            /** Verified */
            verified: string;
            /** Xposed Data */
            xposed_data: string;
            /** Xposed Date */
            xposed_date: string;
            /** Xposed Records */
            xposed_records: number;
            /** Added */
            added: string;
        };
        /** ExposedBreaches */
        ExposedBreaches: {
            /** Breaches Details */
            breaches_details: components["schemas"]["ExposedBreach"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Summary */
        Summary: {
            /** Site */
            site: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    index_emails__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_email_breaches_emails__email__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailBreaches"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_email_breach_analytics_emails_analytics__email__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailBreachAnalytics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_breaches_breaches__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breaches"];
                };
            };
        };
    };
    get_breaches_breaches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breaches"];
                };
            };
        };
    };
    get_breach_breaches__breach_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                breach_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breaches"] | {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_store_store__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    store_breach_store_breach_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
}
