/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExposedOrNotIndexRouteImport } from './routes/exposed-or-not/index'
import { Route as ExposedOrNotEmailsIndexRouteImport } from './routes/exposed-or-not/emails/index'
import { Route as ExposedOrNotBreachesIndexRouteImport } from './routes/exposed-or-not/breaches/index'
import { Route as ExposedOrNotEmailsEmailRouteImport } from './routes/exposed-or-not/emails/$email'
import { Route as ExposedOrNotBreachesDomainRouteImport } from './routes/exposed-or-not/breaches/$domain'

const ContactLazyRouteImport = createFileRoute('/contact')()

const ContactLazyRoute = ContactLazyRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposedOrNotIndexRoute = ExposedOrNotIndexRouteImport.update({
  id: '/exposed-or-not/',
  path: '/exposed-or-not/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposedOrNotEmailsIndexRoute = ExposedOrNotEmailsIndexRouteImport.update({
  id: '/exposed-or-not/emails/',
  path: '/exposed-or-not/emails/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposedOrNotBreachesIndexRoute =
  ExposedOrNotBreachesIndexRouteImport.update({
    id: '/exposed-or-not/breaches/',
    path: '/exposed-or-not/breaches/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExposedOrNotEmailsEmailRoute = ExposedOrNotEmailsEmailRouteImport.update({
  id: '/exposed-or-not/emails/$email',
  path: '/exposed-or-not/emails/$email',
  getParentRoute: () => rootRouteImport,
} as any)
const ExposedOrNotBreachesDomainRoute =
  ExposedOrNotBreachesDomainRouteImport.update({
    id: '/exposed-or-not/breaches/$domain',
    path: '/exposed-or-not/breaches/$domain',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactLazyRoute
  '/exposed-or-not': typeof ExposedOrNotIndexRoute
  '/exposed-or-not/breaches/$domain': typeof ExposedOrNotBreachesDomainRoute
  '/exposed-or-not/emails/$email': typeof ExposedOrNotEmailsEmailRoute
  '/exposed-or-not/breaches': typeof ExposedOrNotBreachesIndexRoute
  '/exposed-or-not/emails': typeof ExposedOrNotEmailsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactLazyRoute
  '/exposed-or-not': typeof ExposedOrNotIndexRoute
  '/exposed-or-not/breaches/$domain': typeof ExposedOrNotBreachesDomainRoute
  '/exposed-or-not/emails/$email': typeof ExposedOrNotEmailsEmailRoute
  '/exposed-or-not/breaches': typeof ExposedOrNotBreachesIndexRoute
  '/exposed-or-not/emails': typeof ExposedOrNotEmailsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactLazyRoute
  '/exposed-or-not/': typeof ExposedOrNotIndexRoute
  '/exposed-or-not/breaches/$domain': typeof ExposedOrNotBreachesDomainRoute
  '/exposed-or-not/emails/$email': typeof ExposedOrNotEmailsEmailRoute
  '/exposed-or-not/breaches/': typeof ExposedOrNotBreachesIndexRoute
  '/exposed-or-not/emails/': typeof ExposedOrNotEmailsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/exposed-or-not'
    | '/exposed-or-not/breaches/$domain'
    | '/exposed-or-not/emails/$email'
    | '/exposed-or-not/breaches'
    | '/exposed-or-not/emails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/exposed-or-not'
    | '/exposed-or-not/breaches/$domain'
    | '/exposed-or-not/emails/$email'
    | '/exposed-or-not/breaches'
    | '/exposed-or-not/emails'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/exposed-or-not/'
    | '/exposed-or-not/breaches/$domain'
    | '/exposed-or-not/emails/$email'
    | '/exposed-or-not/breaches/'
    | '/exposed-or-not/emails/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactLazyRoute: typeof ContactLazyRoute
  ExposedOrNotIndexRoute: typeof ExposedOrNotIndexRoute
  ExposedOrNotBreachesDomainRoute: typeof ExposedOrNotBreachesDomainRoute
  ExposedOrNotEmailsEmailRoute: typeof ExposedOrNotEmailsEmailRoute
  ExposedOrNotBreachesIndexRoute: typeof ExposedOrNotBreachesIndexRoute
  ExposedOrNotEmailsIndexRoute: typeof ExposedOrNotEmailsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposed-or-not/': {
      id: '/exposed-or-not/'
      path: '/exposed-or-not'
      fullPath: '/exposed-or-not'
      preLoaderRoute: typeof ExposedOrNotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposed-or-not/emails/': {
      id: '/exposed-or-not/emails/'
      path: '/exposed-or-not/emails'
      fullPath: '/exposed-or-not/emails'
      preLoaderRoute: typeof ExposedOrNotEmailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposed-or-not/breaches/': {
      id: '/exposed-or-not/breaches/'
      path: '/exposed-or-not/breaches'
      fullPath: '/exposed-or-not/breaches'
      preLoaderRoute: typeof ExposedOrNotBreachesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposed-or-not/emails/$email': {
      id: '/exposed-or-not/emails/$email'
      path: '/exposed-or-not/emails/$email'
      fullPath: '/exposed-or-not/emails/$email'
      preLoaderRoute: typeof ExposedOrNotEmailsEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exposed-or-not/breaches/$domain': {
      id: '/exposed-or-not/breaches/$domain'
      path: '/exposed-or-not/breaches/$domain'
      fullPath: '/exposed-or-not/breaches/$domain'
      preLoaderRoute: typeof ExposedOrNotBreachesDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactLazyRoute: ContactLazyRoute,
  ExposedOrNotIndexRoute: ExposedOrNotIndexRoute,
  ExposedOrNotBreachesDomainRoute: ExposedOrNotBreachesDomainRoute,
  ExposedOrNotEmailsEmailRoute: ExposedOrNotEmailsEmailRoute,
  ExposedOrNotBreachesIndexRoute: ExposedOrNotBreachesIndexRoute,
  ExposedOrNotEmailsIndexRoute: ExposedOrNotEmailsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
