/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExposedOrNotIndexRouteImport } from './routes/api/exposed-or-not/index'
import { Route as ApiExposedOrNotBreachesIndexRouteImport } from './routes/api/exposed-or-not/breaches/index'
import { Route as ApiExposedOrNotBreachesDomainRouteImport } from './routes/api/exposed-or-not/breaches/$domain'

const ContactLazyRouteImport = createFileRoute('/contact')()

const ContactLazyRoute = ContactLazyRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExposedOrNotIndexRoute = ApiExposedOrNotIndexRouteImport.update({
  id: '/api/exposed-or-not/',
  path: '/api/exposed-or-not/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExposedOrNotBreachesIndexRoute =
  ApiExposedOrNotBreachesIndexRouteImport.update({
    id: '/api/exposed-or-not/breaches/',
    path: '/api/exposed-or-not/breaches/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExposedOrNotBreachesDomainRoute =
  ApiExposedOrNotBreachesDomainRouteImport.update({
    id: '/api/exposed-or-not/breaches/$domain',
    path: '/api/exposed-or-not/breaches/$domain',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactLazyRoute
  '/api/exposed-or-not': typeof ApiExposedOrNotIndexRoute
  '/api/exposed-or-not/breaches/$domain': typeof ApiExposedOrNotBreachesDomainRoute
  '/api/exposed-or-not/breaches': typeof ApiExposedOrNotBreachesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactLazyRoute
  '/api/exposed-or-not': typeof ApiExposedOrNotIndexRoute
  '/api/exposed-or-not/breaches/$domain': typeof ApiExposedOrNotBreachesDomainRoute
  '/api/exposed-or-not/breaches': typeof ApiExposedOrNotBreachesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactLazyRoute
  '/api/exposed-or-not/': typeof ApiExposedOrNotIndexRoute
  '/api/exposed-or-not/breaches/$domain': typeof ApiExposedOrNotBreachesDomainRoute
  '/api/exposed-or-not/breaches/': typeof ApiExposedOrNotBreachesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/api/exposed-or-not'
    | '/api/exposed-or-not/breaches/$domain'
    | '/api/exposed-or-not/breaches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/api/exposed-or-not'
    | '/api/exposed-or-not/breaches/$domain'
    | '/api/exposed-or-not/breaches'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/api/exposed-or-not/'
    | '/api/exposed-or-not/breaches/$domain'
    | '/api/exposed-or-not/breaches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactLazyRoute: typeof ContactLazyRoute
  ApiExposedOrNotIndexRoute: typeof ApiExposedOrNotIndexRoute
  ApiExposedOrNotBreachesDomainRoute: typeof ApiExposedOrNotBreachesDomainRoute
  ApiExposedOrNotBreachesIndexRoute: typeof ApiExposedOrNotBreachesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exposed-or-not/': {
      id: '/api/exposed-or-not/'
      path: '/api/exposed-or-not'
      fullPath: '/api/exposed-or-not'
      preLoaderRoute: typeof ApiExposedOrNotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exposed-or-not/breaches/': {
      id: '/api/exposed-or-not/breaches/'
      path: '/api/exposed-or-not/breaches'
      fullPath: '/api/exposed-or-not/breaches'
      preLoaderRoute: typeof ApiExposedOrNotBreachesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exposed-or-not/breaches/$domain': {
      id: '/api/exposed-or-not/breaches/$domain'
      path: '/api/exposed-or-not/breaches/$domain'
      fullPath: '/api/exposed-or-not/breaches/$domain'
      preLoaderRoute: typeof ApiExposedOrNotBreachesDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactLazyRoute: ContactLazyRoute,
  ApiExposedOrNotIndexRoute: ApiExposedOrNotIndexRoute,
  ApiExposedOrNotBreachesDomainRoute: ApiExposedOrNotBreachesDomainRoute,
  ApiExposedOrNotBreachesIndexRoute: ApiExposedOrNotBreachesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
