/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/emails/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index_api_emails__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emails/analytics/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Email Breach Analytics */
        get: operations["get_email_breach_analytics_api_emails_analytics__email__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emails/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Email Breaches */
        get: operations["get_email_breaches_api_emails__email__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/breaches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Breaches */
        get: operations["get_breaches_api_breaches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/breaches/{breach_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Breach */
        get: operations["get_breach_api_breaches__breach_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index Store */
        get: operations["index_store_api_store__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store/breach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Store Breach */
        get: operations["store_breach_api_store_breach_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Certtres */
        get: operations["get_certtres_api_certificates__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Certdata */
        get: operations["get_certdata_api_certificates_inspect_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Score Domain */
        get: operations["score_domain_api_certificates_score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BasicConstraints */
        BasicConstraints: {
            /** Ca */
            ca: boolean | null;
            /** Path Length */
            path_length: number | null;
        };
        /** Breach */
        Breach: {
            /** Breach Id */
            breach_id: string;
            /**
             * Breached Date
             * Format: date
             */
            breached_date: string;
            /** Domain */
            domain: string;
            /** Exposed Data */
            exposed_data: string[];
            /** Exposed Records */
            exposed_records: number | null;
            /** Exposure Description */
            exposure_description: string;
            /** Industry */
            industry: string;
            /** Logo */
            logo: string;
            /** Password Risk */
            password_risk: string;
            /** Reference Url */
            reference_url: string | null;
            /** Searchable */
            searchable: boolean;
            /** Sensitive */
            sensitive: boolean;
            /** Verified */
            verified: boolean;
        };
        /** BreachMetrics */
        BreachMetrics: {
            /** Get Details */
            get_details: string[];
            /** Industry */
            industry: [
                string,
                number
            ][][];
            /** Passwords Strength */
            passwords_strength: {
                [key: string]: number;
            }[];
            /** Risk */
            risk: components["schemas"]["RiskItem"][];
            /** Xposed Data */
            xposed_data: components["schemas"]["XposedRoot"][];
            /** Yearwise Details */
            yearwise_details: {
                [key: string]: number;
            }[];
        };
        /** BreachSmall */
        BreachSmall: {
            /** Breach Id */
            breach_id: string;
            /**
             * Breached Date
             * Format: date
             */
            breached_date: string;
            /** Exposed Records */
            exposed_records: number | null;
            /** Domain */
            domain: string;
            /** Industry */
            industry: string;
        };
        /** Breaches */
        Breaches: {
            /** Exposedbreaches */
            exposedBreaches: components["schemas"]["BreachSmall"][];
        };
        /** CertificateInfo */
        CertificateInfo: {
            /** Serial Number */
            serial_number: string;
            /** Version */
            version: string;
            /** Subject */
            subject: {
                [key: string]: string;
            };
            /** Issuer */
            issuer: {
                [key: string]: string;
            };
            /** Public Key Type */
            public_key_type: string;
            public_key_details: components["schemas"]["PublicKeyDetails"];
            /** Signature Algorithm */
            signature_algorithm: string | null;
            /** Signature Hash */
            signature_hash: string | null;
            /** Not Before */
            not_before: string;
            /** Not After */
            not_after: string;
            /** Days Left */
            days_left: number;
            /** Lifetime Days */
            lifetime_days: number;
            /** Lifetime Used Percent */
            lifetime_used_percent: number | null;
            /** Is Self Signed */
            is_self_signed: boolean;
            subject_alternative_name: components["schemas"]["SubjectAlternativeName"];
            key_usage: components["schemas"]["KeyUsage"] | null;
            /** Extended Key Usage */
            extended_key_usage: string[] | null;
            basic_constraints: components["schemas"]["BasicConstraints"] | null;
            /** Ocsp Urls */
            ocsp_urls: string[];
            /** Issuer Urls */
            issuer_urls: string[];
            /** Crl Urls */
            crl_urls: string[];
            /** Certificate Policies */
            certificate_policies: string[];
            /** Signed Certificate Timestamps */
            signed_certificate_timestamps: components["schemas"]["SignedCertificateTimestamp"][];
        };
        /** CertificateInspectionResponse */
        CertificateInspectionResponse: {
            /** Domain */
            domain: string;
            /**
             * Success
             * @default true
             */
            success: boolean;
            certificate: components["schemas"]["CertificateInfo"];
            tls_connection: components["schemas"]["TLSConnectionInfo"];
        };
        /** EmailBreachAnalytics */
        EmailBreachAnalytics: {
            BreachMetrics: components["schemas"]["BreachMetrics"];
            BreachesSummary: components["schemas"]["Summary"];
            ExposedBreaches: components["schemas"]["ExposedBreaches"];
            /** Exposedpastes */
            ExposedPastes: {
                [key: string]: unknown;
            } | null;
            /** Pastemetrics */
            PasteMetrics: {
                [key: string]: unknown;
            } | null;
            /** Pastessummary */
            PastesSummary: {
                [key: string]: unknown;
            };
        };
        /** EmailBreaches */
        EmailBreaches: {
            /** Breaches */
            breaches: string[][];
            /** Email */
            email: string;
            /** Status */
            status: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Error */
            Error: string;
            /** Email */
            email: string | null;
        };
        /** ExposedBreach */
        ExposedBreach: {
            /** Breach */
            breach: string;
            /** Details */
            details: string;
            /** Domain */
            domain: string;
            /** Industry */
            industry: string;
            /** Logo */
            logo: string;
            /** Password Risk */
            password_risk: string;
            /** References */
            references: string;
            /** Searchable */
            searchable: string;
            /** Verified */
            verified: string;
            /** Xposed Data */
            xposed_data: string;
            /** Xposed Date */
            xposed_date: string;
            /** Xposed Records */
            xposed_records: number;
            /** Added */
            added: string;
        };
        /** ExposedBreaches */
        ExposedBreaches: {
            /** Breaches Details */
            breaches_details: components["schemas"]["ExposedBreach"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KeyUsage */
        KeyUsage: {
            /** Digital Signature */
            digital_signature: boolean | null;
            /** Content Commitment */
            content_commitment: boolean | null;
            /** Key Encipherment */
            key_encipherment: boolean | null;
            /** Data Encipherment */
            data_encipherment: boolean | null;
            /** Key Agreement */
            key_agreement: boolean | null;
            /** Key Cert Sign */
            key_cert_sign: boolean | null;
            /** Crl Sign */
            crl_sign: boolean | null;
            /** Encipher Only */
            encipher_only: boolean | null;
            /** Decipher Only */
            decipher_only: boolean | null;
        };
        /** PublicKeyDetails */
        PublicKeyDetails: {
            /** Key Size */
            key_size: number | null;
            /** Public Exponent */
            public_exponent?: number | null;
            /** Modulus Bits */
            modulus_bits?: number | null;
            /** Curve */
            curve?: string | null;
        };
        /** RiskItem */
        RiskItem: {
            /** Risk Label */
            risk_label: string;
            /** Risk Score */
            risk_score: number;
        };
        /** ScoreResponse */
        ScoreResponse: {
            /** Domain */
            domain: string;
            /** Scores */
            scores: {
                [key: string]: number;
            };
            /** Overall Score */
            overall_score: number;
            /** Explanations */
            explanations: {
                [key: string]: string;
            };
            /** Raw Certificate */
            raw_certificate: {
                [key: string]: unknown;
            };
        };
        /** SignedCertificateTimestamp */
        SignedCertificateTimestamp: {
            /** Version */
            version: number | null;
            /** Log Id */
            log_id: string | null;
            /** Timestamp */
            timestamp: string | null;
            /** Hash Algorithm */
            hash_algorithm: string | null;
            /** Signature Algorithm */
            signature_algorithm: string | null;
        };
        /** SubjectAlternativeName */
        SubjectAlternativeName: {
            /** Dns */
            dns: string[];
            /** Ip */
            ip: string[];
            /** Uri */
            uri: string[];
            /** Email */
            email: string[];
        };
        /** Summary */
        Summary: {
            /** Site */
            site: string;
        };
        /** TLSConnectionInfo */
        TLSConnectionInfo: {
            /** Tls Version */
            tls_version: string | null;
            /** Cipher */
            cipher: unknown[] | null;
            /** Alpn */
            alpn: string | null;
            /** Shared Ciphers */
            shared_ciphers: unknown[] | null;
            /** Compression */
            compression: string | null;
            /** Session Reused */
            session_reused: boolean | null;
            /** Server Hostname */
            server_hostname: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** XposedLeaf */
        XposedLeaf: {
            /** Colname */
            colname: string;
            /** Group */
            group: string;
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /** XposedNode */
        XposedNode: {
            /** Name */
            name: string;
            /** Colname */
            colname: string;
            /** Children */
            children: components["schemas"]["XposedLeaf"][];
        };
        /** XposedRoot */
        XposedRoot: {
            /** Children */
            children: components["schemas"]["XposedNode"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    index_api_emails__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_email_breach_analytics_api_emails_analytics__email__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailBreachAnalytics"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_email_breaches_api_emails__email__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailBreaches"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_breaches_api_breaches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breaches"];
                };
            };
        };
    };
    get_breach_api_breaches__breach_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                breach_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breach"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    index_store_api_store__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    store_breach_api_store_breach_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_certtres_api_certificates__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_certdata_api_certificates_inspect_get: {
        parameters: {
            query: {
                domain: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateInspectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_domain_api_certificates_score_get: {
        parameters: {
            query: {
                domain: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
